root = "."
tmp_dir = "tmp"

[build]
  # PENTING: Arahkan ke cmd/api/main.go, bukan titik (.)
  cmd = "go build -o ./tmp/main ./cmd/api/main.go"
  
  # Lokasi file binary hasil build
  bin = "./tmp/main"
  
  # Nama file binary (opsional)
  full_bin = ""
  
  # File/Folder yang harus diabaikan watcher
  include_ext = ["go", "tpl", "tmpl", "html", "env"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  include_dir = []
  exclude_file = []
  
  # Delay rebuild (ms)
  delay = 1000
  
  # Stop jika error
  stop_on_error = true
  
  # Log file
  log = "air_errors.log"

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true